sonar.projectKey=notes-app
sonar.projectName=notes-app
sonar.projectVersion=1.0

# Paths
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**

# Optional for JS
sonar.language=js
sonar.sourceEncoding=UTF-8

# Test coverage (optional)
sonar.tests=test
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server
sonar.host.url=http://localhost:9000
sonar.token={env:SONAR_TOKEN}
